--- #YAML:1.0
name:               MCE
version:            1.699_003
abstract:           Many-Core Engine for Perl providing parallel capabilities
author:
    - Mario E. Roy <marioeroy AT gmail DOT com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::Deep:           0
    Test::More:           0.45
requires:
    base:          0
    bytes:         0
    Carp:          0
    constant:      0
    Fcntl:         0
    File::Path:    0
    Getopt::Long:  0
    IO::Handle:    0
    overload:      0
    perl:          5.008
    POSIX:         0
    Scalar::Util:  0
    Socket:        0
    Storable:      2.04
    strict:        0
    Symbol:        0
    Time::HiRes:   0
    warnings:      0
resources:
    homepage:    https://github.com/marioroy/mce-perl
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/marioroy/mce-perl
provides:
    MCE:
        file:     lib/MCE.pm
        version:  1.699_003
    MCE::Candy:
        file:     lib/MCE/Candy.pm
        version:  1.699_003
    MCE::Core::Input::Generator:
        file:     lib/MCE/Core/Input/Generator.pm
        version:  1.699_003
    MCE::Core::Input::Handle:
        file:     lib/MCE/Core/Input/Handle.pm
        version:  1.699_003
    MCE::Core::Input::Iterator:
        file:     lib/MCE/Core/Input/Iterator.pm
        version:  1.699_003
    MCE::Core::Input::Request:
        file:     lib/MCE/Core/Input/Request.pm
        version:  1.699_003
    MCE::Core::Input::Sequence:
        file:     lib/MCE/Core/Input/Sequence.pm
        version:  1.699_003
    MCE::Core::Manager:
        file:     lib/MCE/Core/Manager.pm
        version:  1.699_003
    MCE::Core::Validation:
        file:     lib/MCE/Core/Validation.pm
        version:  1.699_003
    MCE::Core::Worker:
        file:     lib/MCE/Core/Worker.pm
        version:  1.699_003
    MCE::Flow:
        file:     lib/MCE/Flow.pm
        version:  1.699_003
    MCE::Grep:
        file:     lib/MCE/Grep.pm
        version:  1.699_003
    MCE::Hobo:
        file:     lib/MCE/Hobo.pm
        version:  1.699_003
    MCE::Loop:
        file:     lib/MCE/Loop.pm
        version:  1.699_003
    MCE::Map:
        file:     lib/MCE/Map.pm
        version:  1.699_003
    MCE::Mutex:
        file:     lib/MCE/Mutex.pm
        version:  1.699_003
    MCE::Queue:
        file:     lib/MCE/Queue.pm
        version:  1.699_003
    MCE::Relay:
        file:     lib/MCE/Relay.pm
        version:  1.699_003
    MCE::Shared:
        file:     lib/MCE/Shared.pm
        version:  1.699_003
    MCE::Shared::Array:
        file:     lib/MCE/Shared/Array.pm
        version:  1.699_003
    MCE::Shared::Base:
        file:     lib/MCE/Shared/Base.pm
        version:  1.699_003
    MCE::Shared::Condvar:
        file:     lib/MCE/Shared/Condvar.pm
        version:  1.699_003
    MCE::Shared::Handle:
        file:     lib/MCE/Shared/Handle.pm
        version:  1.699_003
    MCE::Shared::Hash:
        file:     lib/MCE/Shared/Hash.pm
        version:  1.699_003
    MCE::Shared::Ordhash:
        file:     lib/MCE/Shared/Ordhash.pm
        version:  1.699_003
    MCE::Shared::Queue:
        file:     lib/MCE/Shared/Queue.pm
        version:  1.699_003
    MCE::Shared::Scalar:
        file:     lib/MCE/Shared/Scalar.pm
        version:  1.699_003
    MCE::Shared::Sequence:
        file:     lib/MCE/Shared/Sequence.pm
        version:  1.699_003
    MCE::Shared::Server:
        file:     lib/MCE/Shared/Server.pm
        version:  1.699_003
    MCE::Signal:
        file:     lib/MCE/Signal.pm
        version:  1.699_003
    MCE::Step:
        file:     lib/MCE/Step.pm
        version:  1.699_003
    MCE::Stream:
        file:     lib/MCE/Stream.pm
        version:  1.699_003
    MCE::Subs:
        file:     lib/MCE/Subs.pm
        version:  1.699_003
    MCE::Util:
        file:     lib/MCE/Util.pm
        version:  1.699_003
no_index:
    directory:
        - t
        - inc
        - examples
        - images
    file:
        - bin/mce_grep
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
